### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by crescentke** [yoamomonstruos/tombates.co#1]
How do I get to display my own activity on the change log? It's showing tombates when I deploy it

**Comment by yoamomonstruos** [comment]
Hey @crescentke.

You'd need to connect the actions to connect to an api with your personal data. I should really share the code for the server, but it's not great. For instance, mine is connected to: https://changelog.maisoumenos.xyz 

Sorry, I can't be of more help.

**Comment by crescentke** [comment]
O.k. 
Thanks
